services:

    CoreShop\Payum\CurabillBundle\Extension\InvoiceTransformerExtension:
        arguments:
            - '@coreshop.repository.order'
        tags:
            - { name: payum.extension, alias: curabill_customer_transformer_extension, factory: curabill, gateway: curabill, prepend: false }

    CoreShop\Payum\CurabillBundle\Extension\ConvertPaymentExtension:
        autowire: true
        tags:
            - { name: payum.extension, alias: curabill_language_extension, factory: curabill, gateway: curabill, prepend: false }

    CoreShop\Payum\CurabillBundle\Extension\FailedPaymentExtension:
        arguments:
            - '@pimcore.translator'
        tags:
            - { name: payum.extension, alias: curabill_failed_extension, factory: curabill, gateway: curabill, prepend: false }

    CoreShop\Payum\CurabillBundle\Form\Payment\CurabillType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: curabill }
            - { name: form.type }

    CoreShop\Payum\CurabillBundle\Form\Payment\CurabillSettingsType:
        tags:
            - { name: coreshop.payment.form.settings, payum-factory: curabill }
            - { name: form.type }

    CoreShop\Payum\CurabillBundle\Event\ConfirmEvent:
        public: true
        arguments:
            - '@payum'
            - '@coreshop.repository.payment'

    CoreShop\Payum\CurabillBundle\Event\CancelEvent:
        public: true
        arguments:
            - '@payum'
            - '@coreshop.repository.payment'

    CoreShop\Payum\CurabillBundle\Event\RefundEvent:
        public: true
        arguments:
            - '@payum'
            - '@coreshop.repository.payment'

    payum.curabill_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [DachcomDigital\Payum\Curabill\CurabillGatewayFactory]
        tags:
            - {name: payum.gateway_factory_builder, factory: curabill }
